
# @name get-users
GET http://localhost:3333/users

###

# @name register
POST http://localhost:3333/register
Content-Type: application/json

{
    "name": "Victor Corassa Pinheiro",
    "email": "victorcorassa@gmail.com.br",
    "password": "Master@123"
}

###

